export const TRANSITION_START = 'R5:TRANSITION:START';
export const TRANSITION_SUCCESS = 'R5:TRANSITION:SUCCESS';
export const TRANSITION_ERROR = 'R5:TRANSITION:ERROR';
export const CLEAR_ERROR = 'R5:CLEAR_ERROR';
export const NAVIGATE_TO = 'R5:NAVIGATE_TO';
export const CANCEL_TRANSITION = 'R5:TRANSITION:CANCEL';
